FROM wordpress:php8.3-apache

COPY p360-ai-newsroom /usr/src/wordpress/wp-content/plugins/periodismo360-ai-newsroom
RUN chown -R www-data:www-data /usr/src/wordpress/wp-content/plugins/periodismo360-ai-newsroom
