export type SportsEvent={provider:string;sport:"football"|"baseball"|"basketball";competition:string;externalId:string;startsAt:string;status:string;home:string;away:string;homeScore?:number;awayScore?:number;raw:unknown};

async function json(url:string,headers:Record<string,string>={}){const r=await fetch(url,{headers,signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error(`Sports provider failed ${r.status}`);return r.json();}

export async function fetchMlb(date:string):Promise<SportsEvent[]>{const data:any=await json(`https://statsapi.mlb.com/api/v1/schedule?sportId=1&date=${encodeURIComponent(date)}&hydrate=team`);return (data.dates??[]).flatMap((d:any)=>(d.games??[]).map((g:any)=>({provider:"mlb-statsapi",sport:"baseball",competition:"MLB",externalId:String(g.gamePk),startsAt:g.gameDate,status:g.status?.detailedState??"unknown",home:g.teams.home.team.name,away:g.teams.away.team.name,homeScore:g.teams.home.score,awayScore:g.teams.away.score,raw:g})));}

export async function fetchApiFootball(league:number,season:number,date:string):Promise<SportsEvent[]>{const key=process.env.API_FOOTBALL_KEY;if(!key)throw new Error("API_FOOTBALL_KEY not configured");const data:any=await json(`https://v3.football.api-sports.io/fixtures?league=${league}&season=${season}&date=${encodeURIComponent(date)}`,{"x-apisports-key":key});return (data.response??[]).map((g:any)=>({provider:"api-football",sport:"football",competition:g.league?.name??String(league),externalId:String(g.fixture.id),startsAt:g.fixture.date,status:g.fixture.status?.short??"unknown",home:g.teams.home.name,away:g.teams.away.name,homeScore:g.goals?.home,awayScore:g.goals?.away,raw:g}));}

export async function fetchSportsDataIo(path:string,sport:"basketball"|"baseball",competition:string):Promise<SportsEvent[]>{const key=process.env.SPORTSDATAIO_KEY;if(!key)throw new Error("SPORTSDATAIO_KEY not configured");const base=sport==="basketball"?"https://api.sportsdata.io/v3/nba":"https://api.sportsdata.io/v3/mlb";const data:any[]=await json(`${base}/${path}`,{"Ocp-Apim-Subscription-Key":key});return data.map((g:any)=>({provider:"sportsdataio",sport,competition,externalId:String(g.GameID??g.GlobalGameID),startsAt:g.DateTimeUTC??g.DateTime,status:g.Status??"unknown",home:g.HomeTeam??g.HomeTeamName,away:g.AwayTeam??g.AwayTeamName,homeScore:g.HomeTeamScore,awayScore:g.AwayTeamScore,raw:g}));}
