import fs from 'node:fs';
import { readJson, run } from './lib.mjs';
const cfg=readJson('config/pipeline.json');
const mode=process.argv[2]||'plan';
console.log(`\n${cfg.name}\nEntry: ${cfg.entrySkill}\n`);
for(const [i,s] of cfg.stages.entries()) console.log(`${i+1}. ${s.id}${s.optional?' (optional)':''}: ${s.skills.join(', ')}`);
if(mode==='plan') process.exit(0);
if(mode!=='run') throw new Error('Usage: node scripts/orchestrator.mjs [plan|run]');
run('node scripts/validate-skills.mjs','skill gate');
if(process.env.FIGMA_FILE_KEY) run('node scripts/figma-sync.mjs','Figma sync');
run(process.env.LINT_COMMAND,'lint');
run(process.env.TEST_COMMAND,'tests');
run(process.env.BUILD_COMMAND,'build');
run('node scripts/qa.mjs','QA gate');
if(process.env.DEPLOY_COMMAND) run('node scripts/deploy.mjs','deploy');
if(process.env.WP_PUBLISH==='true') run('node scripts/wordpress-publish.mjs','WordPress publish');
fs.mkdirSync('.pipeline',{recursive:true});
fs.writeFileSync('.pipeline/last-run.json',JSON.stringify({ok:true,finishedAt:new Date().toISOString()},null,2));
console.log('\nPipeline completed.');
